# main paths
data_path: "data"

# test
test: "test.csv"

# exp params
save_path: "Experiments/neural_iono/baseline"
test_name: val

trainer:
  precision: 32
  accelerator: auto
  #  accelerator: gpu
  devices: auto
  #  devices: [0]

weights: "Experiments/neural_iono/baseline/model.ckpt"

dataloader:
  batch_size: 8
  num_workers: 2
