# main paths
data_path: "data"
exp_path: "Experiments"

# train
train: "train.csv"

# validation
val: "val.csv"

# test
test: "test.csv"

# exp params
exp_name: target1_5_e-3
project: neural_iono

trainer:
  precision: 32
  sync_batchnorm: True
  gradient_clip_val: 1.0
  max_epochs: 5
  #accelerator: auto
  accelerator: gpu
  devices: auto
  #  devices: [0]

weights:

dataloader:
  batch_size: 8
  num_workers: 2

optimizer: LBGFS
optimizer_params:
  lr: 0.001

scheduler: cosine
scheduler_params:
  warmup_epochs: 0

checkpoint:
  monitor: MeanAbsoluteError/val
  filename: model
  mode: max

