# main paths
data_path: "data/J0332_train_val_test"
exp_path: "Experiments"

# train
train: "J0332_train.csv"

# validation
val: "J0332_val.csv"

# test
test: "J0332_test.csv"

# exp params
exp_name: model_J0332_5
project: neural_iono

trainer:
  precision: 32
  sync_batchnorm: True
  gradient_clip_val: 1.0
  max_epochs: 5
  #accelerator: auto
  accelerator: gpu
  devices: auto
  #  devices: [0]

weights:

dataloader:
  batch_size: 128
  num_workers: 2

optimizer: adam
optimizer_params:
  lr: 0.01
  weight_decay: 0.01

scheduler: cosine
scheduler_params:
  warmup_epochs: 0

checkpoint:
  monitor: MeanAbsoluteError/val
  filename: model
  mode: min

